# Generated by Django 3.1.2 on 2020-11-11 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_con', '0003_roomtag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='is_possible_join',
            field=models.BooleanField(default=True, verbose_name='募集中'),
        ),
        migrations.AddField(
            model_name='room',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtag',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtag', to='web_con.room'),
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
