# Generated by Django 3.1.2 on 2020-11-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_con', '0004_auto_20201111_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomuser', to='web_con.room'),
        ),
    ]
