# Generated by Django 3.1.3 on 2020-11-11 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_con', '0005_roomuser_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roomtag',
            unique_together={('room', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='roomuser',
            unique_together={('user', 'room')},
        ),
    ]
