# Generated by Django 3.1.3 on 2020-11-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_con', '0008_auto_20201112_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='peer_id',
            field=models.CharField(blank=True, max_length=127, null=True, unique=True),
        ),
    ]
