# Generated by Django 3.1.3 on 2020-11-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_con', '0009_roomuser_peer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomuser',
            name='peer_id',
        ),
    ]
