# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: WebCon

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: "1"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare Application
      # Start DB Container, Django Application, Frontend Application
      run: |
        python -m pip install pipenv
        bash ./bin/setup.sh
    - name: Test Static Check
      run: |
        bash ./bin/check.sh
    - name: Run tests
      run: |
        bash ./bin/test.sh
